<?php

namespace BibliotecaBundle\Repository;

/**
 * LibroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LibroRepository extends \Doctrine\ORM\EntityRepository
{
}
